### ISSUE TITLE
add global readme explaining content of repo + how to use the scripts

### ISSUE THREAD

**Issue by mikaelarguedas** [osrf/osrf_hw#6]

**Comment by adityamadhwa** [comment]
Yep. Look forward to ReadMe file.

**Comment by mikaelarguedas** [comment]
Should be done in the near future. I preferred to fix up those scripts before advertising them for other users.

**Comment by mikaelarguedas** [comment]
First version of the READMEs is now available since 67f8b40299d9de1f5c29e9019cc3bf9f79c59078. Enjoy!
